input_fields: &id_input_fields
  - one_offset_word_index
  - token
  - lemma
  - upos
  - ptb_pos
  - None
  - dep_head
  - dep_rel
  - None3
  - None4
  - source_file
  - part_number
  - zero_offset_word_index
  - token2
  - ptb_pos3
  - parse_bit
  - predicate_lemma
  - predicate_frameset_id
  - word_sense
  - speaker_author
  - named_entities

cache: &id_cache !WholeDatasetCache
  train_path: &idtrainpath scripts/ontonotes_scripts/train.ontonotes.withdep.conll
  dev_path: &iddevpath scripts/ontonotes_scripts/dev.ontonotes.withdep.conll
  test_path: &idtestpath scripts/ontonotes_scripts/test.ontonotes.withdep.conll

disk_reader: !OntonotesReader &id_disk_reader
  args: 
    - device: cuda:0
  train_path: *idtrainpath 
  dev_path: *iddevpath 
  test_path: *idtestpath 
  cache: *id_cache

dataset: !ListDataset
  args: 
    device: cuda:0
  data_loader: *id_disk_reader
  output_dataset: !AnnotationDataset
    args: 
      device: cuda:0
    task: !TokenClassificationTask
      args: 
        device: cuda:0
      task_name: upos
      input_fields: *id_input_fields
  input_datasets:
    - !HuggingfaceData
      args:
        device: cuda:0
      model_string: &model1string bert-base-uncased
      cache: *id_cache
    - !HuggingfaceData
      args:
        device: cuda:0
      model_string: &model2string bert-large-uncased
      cache: *id_cache

model: !ListModel
  args: 
    device: cuda:0
  models:
    - !HuggingfaceModel
        args:
          device: cuda:0
        model_string: *model1string
        trainable: False
        index: 5
    - !HuggingfaceModel
        args:
          device: cuda:0
        model_string: *model2string
        trainable: False
        index: 5
    
probe: !OneWordLinearLabelProbe
  args:
    device: cuda:0
  model_dim: 1024
  label_space_size: 18

regimen: !ProbeRegimen
  args:
    device: cuda:0
  max_epochs: 50
  params_path: params
  reporting_root: &id_reporting_root configs/round1/upos/bert768_bert256/layer5-5.yaml.results

reporter: !IndependentLabelReporter
  args:
    device: cuda:0
  reporting_root: *id_reporting_root
  reporting_methods:
    - label_accuracy
    - v_entropy
